distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Mar 24 22:07:53 2020"
installation_id: Ubuntu_Desktop
rime_version: 1.7.3
sync_dir: "/home/monojo/Dropbox/RimeSync"
update_time: "Mon Mar  1 20:21:22 2021"